#!/bin/bash
#PBS -l nodes=1:ppn=16

sampleid=
threadNum=16
path=/…/

## 1.fastqc

input=$path/00-fastq-truseq/
output=$path/01-fastQC/$sampleid
mkdir -p $output
fq_file=$(find $input -name $sampleid* | sort)
fastqc -o $output --nogroup -t $threadNum -k 8 $fq_file
cd $output
unzip \*.zip
cd

## 2.quality trim cutadapt

output=$path/02-trimming/cutadapt/$sampleid
mkdir -p $output
cutadapt -a file:$trim_fasta -g file:$trim_fasta -A file:$trim_fasta -G file:$trim_fasta -m 50 --trim-n --max-n 0.7 -q 10,10 -u 5 -U 5 -o $output/$sampleid"_R1_filtered.fastq.gz" -p $output/$sampleid"_R2_filtered.fastq.gz" $fq_file


## 3. post trim qc

input=$path/02-trimming/trimmomatic/$sampleid
output=$path/03-postQC/trimmomatic/$sampleid
mkdir -p $output
fastqc -o $output --nogroup -t $threadNum -k 8 $input/*filtered.fastq.gz
cd $output
unzip \*.zip
cd
